src/com/interfaces/Observer.java
Se añade la interfaz "Observer" como una feature a la rama develop.
=> Feat add interface observer

src/main/java/com/model/Room.java
Inicializando la clase Room para hacer la distribución dada por Maven por defecto de los packages.
=> feat (room) start room class in feature/implement_room_class

src/com/interfaces/Observer.java, src/main/java/com/model/Room.java
Actualizando la organización del proyecto
=> Develop con estructura de packages por defecto de Maven

src/main/java/com/model/Room.java
Hecha la clase Room, para que sea funcional faltaría implementar el abstract factory,  y crear Clue, Puzzle, DecorationItem ... pero todo ello estará completo con el abstractFactory
=> feat(room): Add initial Room implementation, pending AbstractFactory

pom.xml
Changes made in pom.xml:
<build>
<resources>
<resource>
<directory>src/main/resources</directory>
<filtering>false</filtering>
</resource>
</resources>
</build>
=> feat(resources): Update pom.xml to include resources directory config

src/main/java/com/interfaces/AbstractFactory.java
Interfaz AbstractFactory para el projecto Escape Room.
=> feat(interface): Add AbstractFactory interface

src/main/java/com/model/Player.java
Player clase añadida con implementación observable.
=> Add player class

src/main/java/com/factory/FactoryProducer.java, src/main/java/com/factory/RoomFactoryEasy.java, src/main/java/com/factory/RoomFactoryHard.java, src/main/java/com/factory/RoomFactoryMedium.java
This PR implements the Abstract Factory design pattern by adding concrete factory classes to the factory package.
Key changes:
- Creates concrete implementations of the AbstractFactory interface
- Adds factory classes for instantiating game objects in a consistent manner
- Ensures encapsulation of object creation logic
- Supports the Open/Closed principle by allowing new factories without modifying existing code
- Maintains loose coupling between client code and concrete implementations
These factories provide a structured way to create families of related objects, making the codebase more maintainable and extensible as we add new game elements.
=> feat(factory): Abstract Factory implementation, creation of room according to its difficulty"

src/main/java/com/observerImplementation/PlayerObserver.java, src/main/java/com/observerImplementation/RoomObservable.java
Refactor de la implementación interfaz observer y creación de sus dos clases (RoomObservable/PlayerObserver).
=> Feature/observer: Refactor the implementation of the observer interface and creation of its two classes (RoomObservable/PlayerObserver).

src/main/java/com/model/Clue.java, src/main/java/com/model/DecorationItem.java, src/main/java/com/model/Puzzle.java
This pull request refactors the core model classes Clue, DecorationItem, and Puzzle to use Lombok annotations, significantly reducing boilerplate code and improving maintainability.
- ✅ Applied @Data, @Builder, @AllArgsConstructor, and @NoArgsConstructor to all three classes.
- ✅ Set default values using @Builder.Default for:
- `revealedClue` in Clue
- `solvedPuzzle` and `clues` in Puzzle
- ✅ Preserved business logic like `addClue()` and `attemptSolutionPuzzle()` in Puzzle.
These changes prepare the model layer for use with the Abstract Factory pattern, allowing flexible instantiation and easier integration with room configuration logic (e.g., RoomFactoryEasy, RoomFactoryHard).
- Implement `createClue()`, `createDecorationItem()`, and `createPuzzle()` in the factories.
Resumen
Esta pull …
=>  Refactor Clue, DecorationItem, and Puzzle with Lombok and Builder support

src/main/java/com/factory/RoomFactoryEasy.java, src/main/java/com/factory/RoomFactoryHard.java, src/main/java/com/factory/RoomFactoryMedium.java
✅ Changes made:
Fixed import statements in RoomFactoryEasy, RoomFactoryMedium, and RoomFactoryHard classes.
Replaced incorrect package paths to enums and model classes (com.model.enums → com.enums, etc.).
📌 Purpose:
Prevent compilation errors caused by incorrect import paths when implementing AbstractFactory.
- Se corrigieron los imports en las clases RoomFactoryEasy, RoomFactoryMedium y RoomFactoryHard.
- Se reemplazaron rutas incorrectas a enums y modelos (`com.model.enums` → `com.enums`, etc.).
Evitar errores de compilación por rutas incorrectas al implementar `AbstractFactory`.
=> Fix: corrected import statements in factory classes

src/main/java/com/model/Clue.java, src/main/java/com/model/DecorationItem.java, src/main/java/com/model/Puzzle.java
- Renamed attributes in `Clue`, `Puzzle`, and `DecorationItem` to match the domain model and UML.
- Removed redundant suffixes (`Clue`, `Puzzle`, etc.) from field names.
- Added `interactive` boolean attribute to `DecorationItem`.
Standardize model classes so they can be used consistently across factories and services, and align the implementation with the team's agreed naming conventions.
- Se renombraron los atributos en `Clue`, `Puzzle` y `DecorationItem` para que coincidan con el modelo de dominio y el UML.
- Se eliminaron los sufijos redundantes (`Clue`, `Puzzle`, etc.) de los nombres de los campos.
- Se añadió el atributo booleano `interactive` a la clase `DecorationItem`.
Estandarizar las clases del modelo para que puedan usarse de forma coherente en las fábricas y servicios, y …
=> Fix: standardize naming in model classes (Clue, Puzzle, DecorationItem)

src/main/java/com/dao/BaseDAO.java, src/main/java/com/dao/CertificateDAOImpl.java, src/main/java/com/dao/ClueDAOImpl.java, src/main/java/com/dao/DAOManager.java, src/main/java/com/dao/DecorationItemDAOImpl.java, src/main/java/com/dao/InMemoryDAOFactory.java, src/main/java/com/dao/PlayerDAOImpl.java, src/main/java/com/dao/RoomDAOImpl.java, src/main/java/com/dao/TicketSaleDAOImpl.java, src/main/java/com/dao/exception/DAOException.java, src/main/java/com/interfaces/CertificateDAO.java, src/main/java/com/interfaces/ClueDAO.java, src/main/java/com/interfaces/DAOFactory.java, src/main/java/com/interfaces/DecorationItemDAO.java, src/main/java/com/interfaces/GenericDAO.java, src/main/java/com/interfaces/PlayerDAO.java, src/main/java/com/interfaces/RoomDAO.java, src/main/java/com/interfaces/TicketSaleDAO.java, src/main/java/com/model/Certificate.java
DAO Implementation for Escape Room Project with Lombok
1. Basic DAO Pattern
Description: Implements a separate DAO class for each domain entity with CRUD operations.
Functionality: Each DAO interface defines standard operations (create, read, update, delete) for a specific entity type, with concrete implementations handling the actual data access.
Use Cases:
RoomDAO: Managing room entities, including creation, retrieval by ID/theme/difficulty, updating properties, and removal.
ClueDAO: Handling clue persistence, including association with specific rooms.
DecorationItemDAO: Managing inventory of decoration items used across rooms.
2. DAO Factory Pattern
Description: Centralizes the creation of DAO instances through a factory class.
Functionality: Provides methods to obtain DAO instances …
=> feat(DAO): Pattern dao implementation with interfaces

src/main/java/com/repository/EscapeRoomRepository.java, src/main/java/com/repository/InventoryRepository.java
Repository Pattern Overview
The Repository pattern creates an abstraction layer between the domain/business logic and data access code. Unlike the DAO pattern which focuses on direct CRUD operations for specific entities, repositories offer domain-oriented collection interfaces that handle complex business operations spanning multiple entities.
Benefits for Our Project
Domain-Focused API: Provides methods that map directly to business requirements like calculateTotalInventoryValue() rather than just basic CRUD operations.
Simplifies Business Logic: Methods like sellTicket() handle multiple steps (finding player, finding room, creating sale record) in one coherent operation.
Encapsulation of Complex Queries: Complex data operations like calculating revenue statistics or filtering rooms by …
=> feat(Repository Pattern): "Add repository pattern classes for database"

src/test/java/com/dao/RoomDAOImplTest.java, src/test/java/com/model/ObserverTest.java, src/test/java/com/model/RoomTest.java
✅ Added Unit Tests
📦 Classes Tested:
Room: tests for adding puzzles, clues and decoration items.
Observer: verifies observer notification behavior, serves for RoomTest.
RoomDAOImpl: verifies room creation and persistence logic.
🎯 Purpose:
Ensure key components behave correctly and regressions are caught early.
✅ Añadidos Tests Unitarios
📦 Clases Probadas:
Room: pruebas de adición de enigmas, pistas y decoraciones.
Observer: verifica el comportamiento de notificación, sirve para RoomTest.
RoomDAOImpl: verifica la lógica de creación y persistencia de salas.
🎯 Propósito:
Asegurar que los componentes clave funcionen correctamente y detectar regresiones a tiempo.
=>  Test: add unit tests for Room, Observer and RoomDAOImpl classes

src/main/java/com/menu/RoomMenu.java, src/main/java/com/service/InventoryService.java, src/main/java/com/service/RoomService.java
This PR implements the complete flow for creating and deleting a Room by ID through the interactive menu.
-Added option **"Create room"++ to RoomMenu switch
- Added option **"Remove room by ID"** to `RoomMenu` switch.
- Implemented `removeRoomById()` method in `RoomService`.
- Refactored `RoomManager` to `RoomService` as part of the service layer reorganization.
This is part of the work toward fulfilling functionality #7 of the project requirements:  
**"Permetre la retirada de sales, pistes o objectes de decoració de l'inventari."**
Room deletion now works through menu → service → DAO, keeping the structure modular and aligned with the new project architecture.
- `FEATURE(RoomMenu): Add 'deleteRoomById' option to RoomMenu switch`
- `FEATURE(Service): implement 'removeRoomById' method in …
=> FEAT(MENU-SERVICE): implement room creation,delete and addition of clue

src/main/java/com/menu/RoomMenu.java, src/main/java/com/service/RoomContentService.java, src/main/java/com/service/RoomService.java
This set of commits finalizes the full implementation of room content management functionality: clues and decoration items can now be added to rooms interactively.
- Added options to `RoomMenu` for:
- Adding thematic clues to a room
- Adding decoration items to a room
- Refactored `RoomService`:
- Separated room creation/deletion from content management
- Clue and decoration logic moved out for better modularity
- Created new `RoomContentService` class:
- Handles logic to add `Clue` and `DecorationItem` objects to a room
- Uses the corresponding `AbstractFactory` based on room difficulty
- Updates room persistence via `InventoryService`
- Enforces **separation of concerns** between room lifecycle and room content
- Improves maintainability and clarity of responsibilities
- Prepares the …
=> feat(Menu-service): implement room content management (add clue and decoration item)

src/main/java/com/menu/RoomMenu.java, src/main/java/com/service/RoomContentService.java
This PR adds the functionality to insert new puzzles into existing rooms via the interactive menu.
- Added option "Add puzzle to a room" in the `RoomMenu`.
- Implemented `addPuzzleToRoom()` in `RoomContentService`, which:
- Prompts the user for a room ID, puzzle description, and solution.
- Validates the room exists.
- Constructs a new `Puzzle` object and adds it to the room.
- Saves the updated room via `InventoryService`.
- Keeps the logic aligned with how clues and decoration items are handled.
- Uses `Room.addPuzzle(...)` to encapsulate addition and trigger notifications.
- Extensible in the future for attaching clues to puzzles if needed.
This completes an essential, though optional, feature in the Escape Room experience to allow richer gameplay through room-specific puzzles.
=> feat: implement puzzle addition to room via RoomContentService

src/main/java/com/menu/InventoryMenu.java, src/main/java/com/service/InventoryContentService.java
This PR introduces the base structure for managing inventory-related actions through a dedicated menu and service class.
- Created `InventoryMenu` class with options to:
- Show inventory summary
- Show total inventory value
- Remove rooms, clues, or decoration items
- Created `InventoryContentService` as the logic layer for inventory operations:
- Connected to `InventoryService` to perform grouped queries and updates
- Prepared to handle functionality #6 from the requirements (inventory grouping)
- Integrated both classes without implementing full logic yet (placeholders added for future development).
- Follows the same service/menu structure as `RoomService` and `RoomContentService`
- Promotes separation of concerns and improves maintainability
- Facilitates testing and future expansion …
=> feat(InventoryMenu): add InventoryMenu and InventoryContentService structure

src/main/java/com/controller/EscapeRoomVirtual.java, src/main/java/com/menu/InventoryMenu.java, src/main/java/com/menu/RoomMenu.java, src/main/java/com/service/InventoryContentService.java
This PR completes the implementation of inventory overview functionality and connects both RoomMenu and InventoryMenu to the main controller class.
- `EscapeRoomVirtual` now invokes:
- `RoomMenu.manageRooms()` from option 2
- `InventoryMenu.manageInventory()` from option 3
- Made `manageRooms()` in `RoomMenu` public to enable external access.
- Implemented two key methods in `InventoryContentService`:
- `showInventorySummary()` – displays grouped counts of rooms, clues, and decorations.
- `showInventoryValue()` – shows the total euro value of the inventory.
Fulfills requirement #6:
> *Display updated inventory showing available quantities of each element (rooms, clues, decorations).*
Also contributes to requirement #1 by fully enabling room management through the main interface.
=> feat(Menu-Service): implement inventory summary and connect menus to EscapeRoomVirtual

src/test/java/com/integration/InventoryIntegrationTest.java, src/test/java/com/integration/RoomIntegrationTest.java, src/test/java/com/integration/TicketCertificateDAOIntegrationTest.java, src/test/java/com/integration/TicketCertificateIntegrationTest.java
This PR adds four integration tests that verify the correct interaction between key model and service components:
- `RoomIntegrationTest`: verifies puzzle solving and observer notification in Room using RoomFactory.
- `InventoryIntegrationTest`: validates the relationship between Room, Clue, and DecorationItem.
- `TicketCertificateIntegrationTest`: checks correct associations between Player, TicketSale, Room, and Certificate.
- `TicketCertificateDAOIntegrationTest`: verifies persistence and retrieval of TicketSales via DAO implementation.
---
- All tests are located in the `com.integration` package to reflect their cross-component nature.
- The fields `private Room room;` in `Clue` and `DecorationItem` are **pending** and will be added in a future PR, along with related refactors and …
=> Add integration tests for Room, Inventory, TicketSale and Certificate flows

src/main/java/com/menu/PlayerMenu.java, src/main/java/com/service/PlayerContentService.java, src/main/java/com/service/RoomContentService.java
This PR introduces full support for player interactions in the Escape Room system and improves consistency in logging across services.
- **PlayerMenu (new)**: 
- Provides interactive options to sell tickets and issue certificates.
- Integrated with `PlayerContentService`.
- **PlayerContentService (new)**: 
- Handles the logic for selling tickets and issuing certificates.
- Replaces `System.out.println` with `Slf4j` logging.
- **RoomContentService (refactor)**:
- Replaced all console outputs with structured logger messages.
- Added helper methods and reused logging constants for clarity.
- Follows existing patterns (`RoomMenu`, `InventoryMenu`) to keep controller logic clean.
- Standardizes logging across menus and services using `Slf4j`.
Covers:
- ✅ Functionality 9: *Generate ticket sales …
=> feat(Menu-service): add player management menu 

src/main/java/com/controller/EscapeRoomVirtual.java, src/main/java/com/service/EscapeRoomService.java
- add viewRevenue() option to main menu.
- implement viewRevenue method in EspaceRoomVirtual
=> Feature(menu-service):  add viewRevenue() option to main menu

src/main/java/com/Main.java, src/main/java/com/application/EscapeRoomApplication.java, src/main/java/com/controller/EscapeRoomVirtual.java, src/main/java/com/enums/Difficulty.java, src/main/java/com/interfaces/DAOFactory.java, src/main/java/com/model/Player.java, src/main/java/com/model/Room.java, src/main/java/com/observer/EventManager.java, src/main/java/com/service/InventoryContentService.java, src/main/java/com/service/RoomService.java
- Implement of menu-demo and last function "handleNotifications". 
- Refactor of icons.
=> Refactor(Menu-service): remove icons from text messages and implement handleNotifications

src/main/java/com/Main.java, src/main/java/com/application/EscapeRoomApplication.java, src/main/java/com/config/DatabaseConnectionManager.java, src/main/java/com/service/InventoryContentService.java, src/main/java/com/service/PlayerContentService.java, src/main/java/com/service/RoomContentService.java, src/main/java/com/util/DatabaseSeeder.java, src/main/java/com/util/LogMessages.java, src/main/resources/database.properties, src/main/resources/init.sql
This PR includes:
- 🔁 Renamed `com.utils` → `com.util` to match project conventions
- 🆕 Added `DatabaseSeeder` utility to load initial test data from `init.sql`
- 📁 Created `src/main/resources/init.sql` to insert default data (players, rooms, clues, puzzles, decorations)
- 🛠️ Updated `EscapeRoomApplication` to automatically seed database on startup
- 🔧 Refactored services to align with the new data structure
- ➕ Added `database.properties` for DB config and integrated with HikariCP
- `Main.java`
- `EscapeRoomApplication.java`
- `DatabaseConnectionManager.java`
- `InventoryContentService.java`
- `PlayerContentService.java`
- `RoomContentService.java`
- `LogMessages.java` (renamed and modified)
- `DatabaseSeeder.java` (new)
- `init.sql` (new)
- `database.properties` (new)
1. Run the …
=> Refactor: Rename util package and add database seeder for initial data

src/main/java/com/service/InventoryContentService.java, src/main/java/com/service/InventoryService.java, src/main/java/com/service/RoomContentService.java
- InventoryContentService creates an instance of InventoryService
- Added method "addClue", "addDecoration" to InventoryService
- Fix decoration not asking for price when created and not adding it to a list
=> Feature/menu service: fixes of some menu functions

src/main/java/com/dao/BaseDAO.java, src/main/java/com/dao/DAOManager.java, src/main/java/com/dao/JdbcDAOFactory.java, src/main/java/com/dao/PlayerDAOImpl.java, src/main/java/com/dao/RoomDAOImpl.java, src/main/java/com/service/PlayerContentService.java
- Migrated `PlayerDAOImpl` and `RoomDAOImpl` from in-memory to JDBC.
- Created new `JdbcDAOFactory` and registered in `DAOManager`.
- Updated `PlayerContentService`:
- Handles non-existing IDs without crashing
- Asks user to re-enter valid Player/Room IDs
- Uses clean logging and avoids stack trace exposure
- Verified DB connection pool works
- Tickets and certificates can now be issued from DB values
Please ensure your `init.sql` includes the required players and rooms with IDs to test properly.
=> Migrate Player & Room DAOs to JDBC + Improve PlayerContentService
